# Server configuration
server:
  port: 8091
  contextPath:

# Spring configuration
spring:
  devtools:
    remote:
      secret: thisismysecret
  jackson:
    serialization:
      INDENT_OUTPUT: true

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

#spring.boot.admin.url: http://localhost:8080
