spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:scheduled
    username: root
    password:
    driverClassName: org.h2.Driver

logging:
  level:
    org.springframework:
      data: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file: dev.local.scheduled.log

---
spring:
  profiles: production
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: password
    driverClassName: oracle.jdbc.OracleDriver

logging:
  level:
    org.springframework:
      data: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file: dev.local.scheduled.log

