server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: taskmgr-jpa
  datasource:
    url: jdbc:mysql://localhost:3306/taskmgr
    username: root
    password: Wp770521
    driver-class: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
